# Generated by Django 5.2.6 on 2025-11-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_scroll_no_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermaster',
            name='customer_bank',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='customer_bankaccountno',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='customer_bankifsc',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='customer_upi',
        ),
    ]
