# Generated by Django 4.2.16 on 2025-11-17 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_customer_challan_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallanInvoice',
            fields=[
                ('challan_invoice_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('selected_challans', models.JSONField(default=list)),
                ('invoice_total', models.FloatField(default=0.0)),
                ('invoice_paid', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suppliermaster')),
            ],
            options={
                'db_table': 'challan_invoice',
                'ordering': ['-invoice_date', '-challan_invoice_id'],
            },
        ),
    ]
