# Generated by Django 4.2.16 on 2025-11-17 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_challan1_is_invoiced'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallanInvoicePaid',
            fields=[
                ('payment_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(default='Cash', max_length=30)),
                ('payment_reference', models.CharField(default='NA', max_length=30)),
                ('challan_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.challaninvoice')),
            ],
            options={
                'db_table': 'challan_invoice_paid',
                'ordering': ['-payment_date'],
            },
        ),
    ]
