# Generated by Django 4.2.16 on 2025-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_invoicepaid_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepaid',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
