# Generated by Django 5.2.6 on 2025-11-23 11:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1000_merge_20251121_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStockSummary',
            fields=[
                ('summary_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('total_batches', models.IntegerField(default=0)),
                ('total_stock', models.FloatField(default=0.0)),
                ('total_value', models.FloatField(default=0.0)),
                ('low_stock_batches', models.IntegerField(default=0)),
                ('expired_batches', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productmaster')),
            ],
            options={
                'db_table': 'batch_stock_summary',
                'ordering': ['product__product_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('inventory_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(help_text='Format: MM-YYYY', max_length=7)),
                ('mrp', models.FloatField(default=0.0)),
                ('purchase_rate', models.FloatField(default=0.0)),
                ('current_stock', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_stock', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_stock', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock_level', models.FloatField(default=10.0, help_text='Minimum stock alert level')),
                ('location', models.CharField(blank=True, default='MAIN', help_text='Storage location', max_length=50)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_sale_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productmaster')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suppliermaster')),
            ],
            options={
                'db_table': 'inventory_master',
                'ordering': ['product__product_name', 'batch_no'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('purchase_return', 'Purchase Return'), ('sales_return', 'Sales Return'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Stock Transfer'), ('damage', 'Damage/Expiry')], max_length=20)),
                ('quantity', models.FloatField()),
                ('unit_rate', models.FloatField(default=0.0)),
                ('total_value', models.FloatField(default=0.0)),
                ('reference_type', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventorymaster')),
            ],
            options={
                'db_table': 'inventory_transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['product', 'batch_no'], name='inventory_m_product_35d9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['expiry_date'], name='inventory_m_expiry__9c0312_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['current_stock'], name='inventory_m_current_0fee67_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymaster',
            constraint=models.UniqueConstraint(fields=('product', 'batch_no'), name='unique_product_batch_inventory'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['inventory', 'transaction_date'], name='inventory_t_invento_95dc66_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_t_transac_bd472b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_t_referen_d76d26_idx'),
        ),
    ]
