# Generated by Django 4.2.16 on 2025-11-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1002_make_supplier_fields_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challaninvoicepaid',
            name='challan_invoice',
        ),
        migrations.RemoveField(
            model_name='saleschallaninvoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='saleschallaninvoice',
            name='invoice_series',
        ),
        migrations.RemoveField(
            model_name='saleschallaninvoicepaid',
            name='sales_challan_invoice',
        ),
        migrations.DeleteModel(
            name='ChallanInvoice',
        ),
        migrations.DeleteModel(
            name='ChallanInvoicePaid',
        ),
        migrations.DeleteModel(
            name='SalesChallanInvoice',
        ),
        migrations.DeleteModel(
            name='SalesChallanInvoicePaid',
        ),
    ]
