# Generated by Django 4.2.16 on 2025-11-26 15:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1003_remove_challan_invoice_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIssueMaster',
            fields=[
                ('issue_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('issue_no', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('issue_type', models.CharField(choices=[('damage', 'Damage'), ('expiry', 'Expiry'), ('theft', 'Theft'), ('loss', 'Loss'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Transfer Out'), ('sample', 'Sample Given'), ('other', 'Other')], max_length=20)),
                ('total_value', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_issue_master',
                'ordering': ['-issue_date', '-issue_id'],
            },
        ),
        migrations.CreateModel(
            name='StockIssueDetail',
            fields=[
                ('detail_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(help_text='Format: MM-YYYY', max_length=7)),
                ('quantity_issued', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_rate', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.stockissuemaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productmaster')),
            ],
            options={
                'db_table': 'stock_issue_detail',
                'ordering': ['detail_id'],
            },
        ),
    ]
