# Generated by Django 4.2.16 on 2025-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1005_add_challan_transaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemaster',
            name='rate_a',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='rate_b',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='rate_c',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='supplierchallanmaster',
            name='rate_a',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='supplierchallanmaster',
            name='rate_b',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='supplierchallanmaster',
            name='rate_c',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
