# Generated by Django 4.2.16 on 2025-11-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1011_inventorytransaction_batch_no_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS inventory_transaction;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS inventory_master;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS batch_stock_summary;",
            reverse_sql="",
        ),
    ]
