# Generated by Django 5.2.6 on 2025-12-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_cgst_sgst_to_purchase_return'),
        ('core', '1012_drop_inventory_tables'),
    ]

    operations = [
    ]
