# Generated by Django 5.2.6 on 2025-12-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_scheme_charges_from_purchase_return'),
        ('core', '1013_merge_20251202_2124'),
    ]

    operations = [
    ]
