# Generated by Django 4.2.16 on 2025-12-14 18:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1017_add_return_reason_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraEntry',
            fields=[
                ('contra_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contra_no', models.CharField(max_length=20, unique=True)),
                ('contra_date', models.DateField(default=django.utils.timezone.now)),
                ('contra_type', models.CharField(choices=[('BANK_TO_CASH', 'Bank to Cash'), ('CASH_TO_BANK', 'Cash to Bank')], max_length=20)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('from_account', models.CharField(help_text="Bank name or 'Cash'", max_length=100)),
                ('to_account', models.CharField(help_text="Bank name or 'Cash'", max_length=100)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contra Entry',
                'verbose_name_plural': 'Contra Entries',
                'db_table': 'contra_entry',
                'ordering': ['-contra_date', '-contra_id'],
            },
        ),
    ]
