# Generated by Django 5.2.6 on 2025-12-17 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1018_contraentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('stock_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiry_date', models.CharField(blank=True, help_text='Format: MM-YYYY', max_length=7)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_a', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_b', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_c', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventory', to='core.productmaster')),
            ],
            options={
                'db_table': 'stock_inventory',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['product', 'batch_no'], name='idx_product_batch'), models.Index(fields=['current_stock'], name='idx_current_stock')],
                'unique_together': {('product', 'batch_no')},
            },
        ),
    ]
