# Generated by Django 4.2.16 on 2025-12-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1023_alter_stockinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryCache',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory_cache', serialize=False, to='core.productmaster')),
                ('total_stock', models.FloatField(db_index=True, default=0, help_text='Total stock across all batches')),
                ('total_batches', models.IntegerField(default=0, help_text='Number of active batches')),
                ('avg_mrp', models.FloatField(default=0, help_text='Average MRP across batches')),
                ('avg_purchase_rate', models.FloatField(default=0, help_text='Average purchase rate')),
                ('total_stock_value', models.FloatField(default=0, help_text='Total stock value (stock × MRP)')),
                ('stock_status', models.CharField(db_index=True, default='out_of_stock', help_text='in_stock, low_stock, out_of_stock', max_length=20)),
                ('has_expired_batches', models.BooleanField(db_index=True, default=False)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'product_inventory_cache',
                'indexes': [models.Index(fields=['stock_status', 'total_stock'], name='product_inv_stock_s_f6bd53_idx'), models.Index(fields=['has_expired_batches'], name='product_inv_has_exp_d4f590_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchInventoryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(db_index=True, max_length=20)),
                ('expiry_date', models.CharField(help_text='Format: MM-YYYY', max_length=7)),
                ('current_stock', models.FloatField(db_index=True, default=0)),
                ('mrp', models.FloatField(default=0)),
                ('purchase_rate', models.FloatField(default=0)),
                ('rate_a', models.FloatField(default=0)),
                ('rate_b', models.FloatField(default=0)),
                ('rate_c', models.FloatField(default=0)),
                ('is_expired', models.BooleanField(db_index=True, default=False)),
                ('expiry_status', models.CharField(default='valid', help_text='expired, expiring_soon, valid', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_caches', to='core.productmaster')),
            ],
            options={
                'db_table': 'batch_inventory_cache',
                'ordering': ['expiry_date', 'batch_no'],
                'indexes': [models.Index(fields=['product', 'current_stock'], name='batch_inven_product_023fdd_idx'), models.Index(fields=['is_expired'], name='batch_inven_is_expi_807cb4_idx'), models.Index(fields=['expiry_date'], name='batch_inven_expiry__31a7c8_idx'), models.Index(fields=['batch_no'], name='batch_inven_batch_n_9416c7_idx')],
                'unique_together': {('product', 'batch_no', 'expiry_date')},
            },
        ),
    ]
