# Generated by Django 4.2.16 on 2025-12-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1023_increase_stock_status_length'),
        ('core', '1024_productinventorycache_batchinventorycache'),
    ]

    operations = [
    ]
