# Generated by Django 5.2.6 on 2025-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_supplier_challan_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchasemaster',
            name='returnproduct_expiry',
            field=models.DateField(help_text='Expiry date'),
        ),
    ]
