# Generated by Django 5.2.6 on 2025-11-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_invoice_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceseries',
            name='series_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
