# Generated by Django 5.2.6 on 2025-11-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_supplier_challan_master'),
        ('core', '0044_alter_invoiceseries_series_id'),
    ]

    operations = [
    ]
