# Generated by Django 5.2.6 on 2025-11-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_supplier_challan_master_table'),
        ('core', '0045_merge_20251114_1238'),
    ]

    operations = [
    ]
