# Generated by Django 4.2.16 on 2025-11-15 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_merge_20251114_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerChallan',
            fields=[
                ('customer_challan_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_challan_no', models.CharField(max_length=50, unique=True)),
                ('customer_challan_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_transport_charges', models.FloatField(default=0.0)),
                ('challan_invoice_paid', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challan_invoice_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoiceseries')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customermaster')),
            ],
            options={
                'db_table': 'customer_challan',
                'ordering': ['-customer_challan_date', '-customer_challan_id'],
            },
        ),
    ]
