# Generated by Django 4.2.16 on 2025-11-15 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_customerchallan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerChallanMaster',
            fields=[
                ('customer_challan_master_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_challan_no', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('product_company', models.CharField(max_length=200)),
                ('product_packing', models.CharField(max_length=20)),
                ('product_batch_no', models.CharField(max_length=20)),
                ('product_expiry', models.CharField(help_text='Format: MM-YYYY', max_length=7)),
                ('product_mrp', models.FloatField()),
                ('sale_rate', models.FloatField()),
                ('sale_quantity', models.FloatField()),
                ('sale_discount', models.FloatField(default=0.0)),
                ('sale_cgst', models.FloatField(default=2.5)),
                ('sale_sgst', models.FloatField(default=2.5)),
                ('sale_total_amount', models.FloatField()),
                ('sales_entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate_applied', models.CharField(blank=True, default='NA', max_length=10)),
                ('customer_challan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerchallan')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customermaster')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productmaster')),
            ],
            options={
                'db_table': 'customer_challan_master',
                'ordering': ['-sales_entry_date'],
            },
        ),
    ]
