# Generated by Django 4.2.16 on 2025-11-15 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_customerchallanmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallanSeries',
            fields=[
                ('series_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Challan Series',
            },
        ),
        migrations.RemoveField(
            model_name='customerchallan',
            name='challan_invoice_series',
        ),
        migrations.AddField(
            model_name='customerchallan',
            name='challan_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.challanseries'),
        ),
    ]
