# Generated by Django 4.2.16 on 2025-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_challaninvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan1',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
