# Generated by Django 5.2.6 on 2025-11-17 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_create_default_invoice_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerchallan',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SalesChallanInvoice',
            fields=[
                ('sales_challan_invoice_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('selected_challans', models.JSONField(default=list)),
                ('invoice_total', models.FloatField(default=0.0)),
                ('invoice_paid', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customermaster')),
                ('invoice_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoiceseries')),
            ],
            options={
                'db_table': 'sales_challan_invoice',
                'ordering': ['-invoice_date', '-sales_challan_invoice_id'],
            },
        ),
        migrations.CreateModel(
            name='SalesChallanInvoicePaid',
            fields=[
                ('payment_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(default='Cash', max_length=30)),
                ('payment_reference', models.CharField(default='NA', max_length=30)),
                ('sales_challan_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.saleschallaninvoice')),
            ],
            options={
                'db_table': 'sales_challan_invoice_paid',
                'ordering': ['-payment_date'],
            },
        ),
    ]
