# Generated by Django 5.2.6 on 2025-11-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_customerchallan_is_invoiced_saleschallaninvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaster',
            name='supplier_branch',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
    ]
