# Generated by Django 5.2.6 on 2025-11-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_suppliermaster_supplier_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepaid',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
