# Generated by Django 5.2.6 on 2025-11-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_delete_paymentmaster'),
        ('core', '0058_remove_invoicepaid_bank_name_and_more'),
    ]

    operations = [
    ]
