# Generated by Django 5.2.6 on 2025-11-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_merge_20251120_2309'),
        ('core', '0999_remove_receipt_master'),
    ]

    operations = [
    ]
