# Generated by Django 4.2.16 on 2025-11-28 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1008_add_source_challan_to_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierChallanMaster2',
            fields=[
                ('challan_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_challan_no', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('product_company', models.CharField(max_length=200)),
                ('product_packing', models.CharField(max_length=20)),
                ('product_batch_no', models.CharField(max_length=20)),
                ('product_expiry', models.CharField(help_text='Format: MM-YYYY', max_length=7)),
                ('product_mrp', models.FloatField()),
                ('product_purchase_rate', models.FloatField()),
                ('product_quantity', models.FloatField()),
                ('product_scheme', models.FloatField(default=0.0)),
                ('product_discount', models.FloatField(default=0.0)),
                ('product_transportation_charges', models.FloatField(default=0.0)),
                ('actual_rate_per_qty', models.FloatField(default=0.0)),
                ('product_actual_rate', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('challan_entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cgst', models.FloatField(default=2.5)),
                ('sgst', models.FloatField(default=2.5)),
                ('challan_calculation_mode', models.CharField(default='flat', max_length=10)),
                ('rate_a', models.FloatField(blank=True, default=0.0)),
                ('rate_b', models.FloatField(blank=True, default=0.0)),
                ('rate_c', models.FloatField(blank=True, default=0.0)),
                ('product_challan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.challan1')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productmaster')),
                ('product_suppliername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suppliermaster')),
            ],
            options={
                'db_table': 'supplier_challan_master2',
                'ordering': ['-challan_entry_date'],
            },
        ),
    ]
