# Generated by Django 4.2.16 on 2025-11-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1010_customerchallanmaster2'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='batch_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventorymaster'),
        ),
    ]
