# Generated by Django 4.2.16 on 2025-12-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1025_merge_20251219_2027'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS inventory_calculation CASCADE;",
            reverse_sql="CREATE TABLE inventory_calculation (id SERIAL PRIMARY KEY);"
        ),
    ]
