# Generated by Django 4.2.16 on 2026-01-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1026_remove_inventory_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_user',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
