from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from datetime import datetime
from io import BytesIO
import csv

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from .models import ProductMaster, Pharmacy_Details
from .utils import get_stock_status

def get_filtered_products(request):
    """Get products based on user's filters and search"""
    sort_by = request.GET.get('sort', 'productid')
    search_query = request.GET.get('search', '').strip()
    
    sort_options = {
        'name': 'product_name',
        'company': 'product_company',
        'supplier': 'product_company',
        'category': 'product_category',
        'stock': 'productid',
        'productid': 'productid'
    }
    
    order_field = sort_options.get(sort_by, 'productid')
    products = ProductMaster.objects.all().order_by(order_field)
    
    if search_query:
        search_words = search_query.split()
        search_filter = Q()
        for word in search_words:
            word_filter = (
                Q(product_name__icontains=word) |
                Q(product_company__icontains=word) |
                Q(product_salt__icontains=word) |
                Q(product_packing__icontains=word) |
                Q(product_category__icontains=word) |
                Q(product_barcode__icontains=word)
            )
            search_filter &= word_filter
        products = products.filter(search_filter)
    
    products_with_stock = []
    for product in products:
        try:
            stock_info = get_stock_status(product.productid)
            product.current_stock = stock_info.get('current_stock', 0)
        except:
            product.current_stock = 0
        products_with_stock.append(product)
    
    if sort_by == 'stock':
        products_with_stock.sort(key=lambda p: p.current_stock, reverse=True)
    
    return products_with_stock

@login_required
def export_products_pdf(request):
    """Export products to PDF with ReportLab - respects filters and pagination"""
    products = get_filtered_products(request)
    pharmacy = Pharmacy_Details.objects.first()
    
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'inline; filename="products_{datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf"'
    
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(A4), topMargin=0.5*inch, bottomMargin=0.5*inch)
    elements = []
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#007bff'),
        spaceAfter=10,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#666666'),
        spaceAfter=20,
        alignment=TA_CENTER
    )
    
    elements.append(Paragraph(f"{pharmacy.pharmacy_name if pharmacy else 'MedicVista'}", title_style))
    elements.append(Paragraph("Products Master List", subtitle_style))
    
    info_data = [
        ['Generated:', datetime.now().strftime('%d %B %Y, %I:%M %p'), 'Total Products:', str(len(products))],
        ['Generated By:', request.user.get_full_name() or request.user.username, 'Search Filter:', request.GET.get('search', 'None')],
    ]
    
    info_table = Table(info_data, colWidths=[1.2*inch, 2.5*inch, 1.2*inch, 2*inch])
    info_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#007bff')),
        ('TEXTCOLOR', (2, 0), (2, -1), colors.HexColor('#007bff')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (2, 0), (2, -1), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 0.3*inch))
    
    products_per_page = 30
    total_pages = (len(products) + products_per_page - 1) // products_per_page
    
    for page_num in range(total_pages):
        start_idx = page_num * products_per_page
        end_idx = min(start_idx + products_per_page, len(products))
        page_products = products[start_idx:end_idx]
        
        data = [['#', 'Product Name', 'Company', 'Packing', 'Category', 'HSN', 'GST%', 'Barcode', 'Stock']]
        
        for idx, product in enumerate(page_products, start=start_idx + 1):
            stock_color = colors.red if product.current_stock <= 0 else (colors.orange if product.current_stock <= 10 else colors.green)
            data.append([
                str(idx),
                Paragraph(product.product_name[:35], styles['Normal']),
                product.product_company[:20],
                product.product_packing or '-',
                product.product_category[:15] if product.product_category else '-',
                product.product_hsn or '-',
                f"{product.product_hsn_percent}%" if product.product_hsn_percent else '-',
                product.product_barcode[:12] if product.product_barcode else '-',
                str(int(product.current_stock))
            ])
        
        table = Table(data, colWidths=[0.4*inch, 2.5*inch, 1.5*inch, 0.8*inch, 1*inch, 0.8*inch, 0.5*inch, 1*inch, 0.6*inch])
        
        table_style = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#007bff')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('ALIGN', (0, 1), (0, -1), 'CENTER'),
            ('ALIGN', (-1, 1), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ]
        
        for row_idx, product in enumerate(page_products, start=1):
            if product.current_stock <= 0:
                table_style.append(('TEXTCOLOR', (-1, row_idx), (-1, row_idx), colors.red))
                table_style.append(('FONTNAME', (-1, row_idx), (-1, row_idx), 'Helvetica-Bold'))
            elif product.current_stock <= 10:
                table_style.append(('TEXTCOLOR', (-1, row_idx), (-1, row_idx), colors.orange))
        
        table.setStyle(TableStyle(table_style))
        elements.append(table)
        
        footer_text = f"Page {page_num + 1} of {total_pages} | Products {start_idx + 1}-{end_idx} of {len(products)}"
        footer = Paragraph(footer_text, ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, alignment=TA_CENTER, textColor=colors.grey))
        elements.append(Spacer(1, 0.2*inch))
        elements.append(footer)
        
        if page_num < total_pages - 1:
            elements.append(PageBreak())
    
    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response

@login_required
def export_products_excel(request):
    """Export products to Excel/CSV - respects filters"""
    products = get_filtered_products(request)
    pharmacy = Pharmacy_Details.objects.first()
    
    response = HttpResponse(content_type='text/csv; charset=utf-8')
    response['Content-Disposition'] = f'attachment; filename="products_{datetime.now().strftime("%Y%m%d_%H%M%S")}.csv"'
    response.write('\ufeff')
    
    writer = csv.writer(response)
    writer.writerow([f'{pharmacy.pharmacy_name if pharmacy else "MedicVista"} - Products Master List'])
    writer.writerow([f'Generated: {datetime.now().strftime("%d %B %Y, %I:%M %p")}'])
    writer.writerow([f'By: {request.user.get_full_name() or request.user.username}'])
    writer.writerow([f'Search Filter: {request.GET.get("search", "None")}'])
    writer.writerow([f'Sort By: {request.GET.get("sort", "Product ID")}'])
    writer.writerow([])
    writer.writerow(['#', 'Product Name', 'Company', 'Packing', 'Salt', 'Category', 'HSN', 'GST%', 'Barcode', 'Stock'])
    
    for idx, product in enumerate(products, start=1):
        writer.writerow([
            idx,
            product.product_name,
            product.product_company,
            product.product_packing or '-',
            product.product_salt or '-',
            product.product_category or '-',
            product.product_hsn or '-',
            f"{product.product_hsn_percent}%" if product.product_hsn_percent else '-',
            product.product_barcode or '-',
            f"{product.current_stock:.0f}"
        ])
    
    writer.writerow([])
    writer.writerow([f'Total: {len(products)} products'])
    return response
